import {
  Twitter,
  Github,
  Linkedin,
  Mail,
  ExternalLink,
  Phone,
  MapPin,
  ChevronRight,
  Calendar,
  User,
  FileCode,
  Terminal,
  Code,
  CodeIcon,
  GraduationCap,
  BookOpen,
  Laptop,
  Flame,
  ArrowRight,
  RefreshCw,
  Clock,
  Shield,
  Cpu,
  Server,
  BarChart,
  Database,
  Lock,
  Search,
  type LucideProps
} from "lucide-react"

export const Icons = {
  logo: CodeIcon,
  twitter: Twitter,
  gitHub: Github,
  linkedin: Linkedin,
  mail: Mail,
  link: ExternalLink,
  phone: Phone,
  location: MapPin,
  chevronRight: ChevronRight,
  calendar: Calendar,
  user: User,
  fileCode: FileCode,
  terminal: Terminal,
  code: Code,
  codeSquare: CodeIcon,
  education: GraduationCap,
  book: BookOpen,
  laptop: Laptop,
  flame: Flame,
  arrowRight: ArrowRight,
  refresh: RefreshCw,
  clock: Clock,
  shield: Shield,
  cpu: Cpu,
  server: Server,
  chart: BarChart,
  database: Database,
  lock: Lock,
  search: Search,
}